# A Workflow for adjusting the version number of the next release

name: Set next version
run-name: Set next version (${{ inputs.part }})

on:
  workflow_dispatch:
    inputs:
      part:
        description: "Part to increment: Major, Minor, Patch or the next release, e.g. 1.2.3"
        required: true
        default: Minor

permissions:
  contents: read

concurrency: "${{ github.repository }}-versioning"

jobs:
  version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          token: ${{ secrets.TRIGGER_GITHUB_TOKEN }}
      - name: Fetch version history
        run: git fetch --tags --unshallow
      - name: Set up JDK
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: gradle
      - name: Increment version
        if: contains(fromJson('["Major", "Minor", "Patch"]'), github.event.inputs.part)
        run: |
          # The following command will trigger the build.yml workflow as it pushes a alpha tag
          ./gradlew markNextVersion -Prelease.incrementer=increment${{ github.event.inputs.part }}
      - name: Set next version
        if: (!contains(fromJson('["Major", "Minor", "Patch"]'), github.event.inputs.part))
        run: |
          # The following command will trigger the build.yml workflow as it pushes a alpha tag
          ./gradlew markNextVersion -Prelease.version=${{ github.event.inputs.part }}
